apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dataloader.fontys.s66.bied
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: fontys.s66.bied
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                loaderType:
                  type: string
                cronSpec:
                  type: string
                database:
                  type: object
                  properties:
                    driver:
                      type: string
                    # should point to a secret
                    name:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                    host:
                      type: string
                    port:
                      type: string
                    # should point to a secret
                    password:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: dataloaders
    # singular name to be used as an alias on the CLI and for display
    singular: dataloader
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DataLoader
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dl