apiVersion: v1
kind: Service
metadata:
  namespace: authentication
  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 3010
    targetPort: 3010
  selector:
    io.kompose.service: authentication
