apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication
  template:
    metadata:
      labels:
        io.kompose.service: authentication
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configmap":{"name":"authentication-bied-set","items":[{"key":"authentication.pb","path":"authentication.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
    spec:
      containers:
        - name: authentication
          image: "{{ .Values.global.services.authentication.name }}:{{ .Values.global.services.authentication.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - containerPort: 3010
          env:
            - name: ASPNETCORE_URLS
              value: http://*:3010
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
