apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: authentication-db
  name: authentication-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication-db
  template:
    metadata:
      labels:
        io.kompose.service: authentication-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: authentication-db
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: SA_PASSWORD
              value: Superl33tpassw0rd!
