buildpath: <projectDir>
environment: dev
scripts:
  - name: start-minikube
    command: bash
    args: ["./scripts/start-minikube"]
    bindings: []
  - name: set-minikube-context
    command: bash
    args: ["./scripts/set-minikube-context"]
    bindings: ["pre-build", "pre-deploy"]
    environments: ["dev"]
template: project
version: v0.0.0+unreleased
buildPath: "<projectDir>"
repository: "eu.gcr.io/s66-2-271821/"
