buildpath: <projectDir>
environment: dev
scripts:
  - name: start-minikube
    command: bash
    args: ["./scripts/start-minikube"]
    bindings: []
  - name: set-minikube-context
    command: bash
    args: ["./scripts/set-minikube-context"]
    bindings: ["pre-build", "pre-deploy"]
    environments: ["dev"]
  - name: create-proto-configmaps
    command: bash
    args: ["./scripts/create-proto-configmaps"]
    bindings: ["pre-deploy"]
  - name: create-user-service-keys
    command: bash
    args: ["./scripts/create-proto-configmaps"]
    bindings: ["pre-deploy"]
  - name: ip
    command: bash
    args: ["./scripts/ip"]
  - name: set-deploy-host
    command: bash
    args:
      ["-c", "echo KIP_HELM_ARGS=--set global.serverHost=$(kip run ip -- -h)"]
    bindings: ["pre-deploy"]
    environments: ["dev"]
template: project
version: v0.0.0+unreleased
buildPath: "<projectDir>"
repository: "eu.gcr.io/s66-2-271821/"
