replicaCount: 1

image:
  pullPolicy: IfNotPresent

containerPort: 80
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "research-ui"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  port: 80
  targetPort: 80
