using System;
using System.Threading;
using System.Collections.Generic;
using System.Threading.Tasks;
using Questionnaire.Persistence.Repositories;
using Questionnaire.Persistence.Entities;

namespace ApiService_tests.mock
{
    public class MockQuestionnaireRepository : IQuestionnaireRepository {
        
        public async Task<QuestionnaireEntity> GetQuestionnaireById(String id)
        {
            return await new Task<QuestionnaireEntity>(() => {
                QuestionnaireEntity q = new QuestionnaireEntity();
                q.Name = "mock";
                q.Description = "Generated by MockQuestionnaireRepository";
                q.Questions = new List<QuestionEntity>();
                return q;
            });
        }
        public async Task<IEnumerable<QuestionnaireEntity>> GetQuestionnaires()
        {
            return await new Task<IEnumerable<QuestionnaireEntity>>(() => {
                return new List<QuestionnaireEntity>();
            });
        }
        public async Task<QuestionnaireEntity> CreateQuestionnaire(QuestionnaireEntity questionnaire)
        {
            return await new Task<QuestionnaireEntity>(() => {
                return questionnaire;
            });
        }
        public async Task<QuestionnaireEntity> UpdateQuestionnaire(QuestionnaireEntity questionnaire)
        {
            return await new Task<QuestionnaireEntity>(() => {
                return questionnaire;
            });
        }
        public async Task DeleteQuestionnaire(string id)
        {
            await new Task(() => {});
        }

    }
}