apiVersion: v1
kind: Service
metadata:
  name: {{ include "datasource-ui.fullname" . }}
  labels:
    {{- include "datasource-ui.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "datasource-ui.selectorLabels" . | nindent 4 }}
