apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "datasource-ui.fullname" . }}
spec:
  gateways:
    - bied-gateway
  hosts:
    - "{{ .Values.global.datasources_ui.host }}"
  http:
    - match:
        - uri:
            prefix: "{{ .Values.global.datasources_ui.route }}"
      rewrite:
        uri: /
      route:
        # routes it toward this host. Usually a Kubernetes native 'Service', this should be a FQDN in production
        - destination:
            host: {{ include "datasource-ui.fullname" . }}
            port:
              number: 80