export enum QuestionType {
  DATE = 'DATE',
  LIKERT = 'LIKERT',
  LIKERT_GROUP = 'LIKERT_GROUP',
  RADIO = 'RADIO',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  DROPDOWN = 'DROPDOWN',
  NUMERICAL = 'NUMERICAL',
  OPEN_TEXT = 'OPEN_TEXT',
  TIME = 'TIME',
}
