// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using research_service.Persistence.Context;

namespace research_service.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20200518080351_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("research_service.Persistence.Entities.ResearchDatasource", b =>
                {
                    b.Property<Guid>("ResearchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DatasourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResearchId", "DatasourceId");

                    b.ToTable("ResearchDatasource");
                });

            modelBuilder.Entity("research_service.Persistence.Entities.ResearchEditor", b =>
                {
                    b.Property<Guid>("ResearchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResearchId", "UserId");

                    b.ToTable("ResearchEditor");
                });

            modelBuilder.Entity("research_service.Persistence.Entities.ResearchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Researches");
                });

            modelBuilder.Entity("research_service.Persistence.Entities.ResearchDatasource", b =>
                {
                    b.HasOne("research_service.Persistence.Entities.ResearchEntity", "Research")
                        .WithMany("ResearchDataSources")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("research_service.Persistence.Entities.ResearchEditor", b =>
                {
                    b.HasOne("research_service.Persistence.Entities.ResearchEntity", "Research")
                        .WithMany("ResearchEditors")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
