version: "3.7"

services:
  authentication-database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "2434:1433"
    environment:
      SA_PASSWORD: "password1!"
      ACCEPT_EULA: "y"
    volumes:
      - "authentication_database_data:/var/lib/database/data"
volumes:
  authentication_database_data:
