apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: {{ .Values.name }}
spec:
  databaseSecret:
    secretName: mysql-datasource-secret
  version: "8.0-v2"
  storageType: Durable
  storage:
    storageClassName: {{ .Values.global.storageClassName }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storage }}    
  podTemplate:
    metadata:
        labels:
          app: mysql
        annotations:
          sidecar.istio.io/inject: "false"
    spec:
        args:
        - --default-authentication-plugin=mysql_native_password
  terminationPolicy: Delete
  init:
    scriptSource:
      configMap:
        name: init-sql
