apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: {{ .Values.name }}
spec:
  databaseSecret:
    secretName: mysql-datasource-secret
  version: "8.0-v2"
  storageType: Durable
  storage:
    storageClassName: {{ .Values.global.storageClassName }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storage }}    
  podTemplate:
    metadata:
      labels:
        app: mysql
    spec:
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_HOST
          value: '%'
  terminationPolicy: Delete
  init:
    scriptSource:
      configMap:
        name: init-sql
