# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: baget-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/var/baget"
#     type: DirectoryOrCreate
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baget-pv-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi