# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: nugetregistry
#   name: baget-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/var/baget"
#     type: DirectoryOrCreate
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nugetregistry
  name: baget-pv-claim
spec:
  storageClassName: custom-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
