apiVersion: v1
kind: Service
metadata:
  namespace: nugetregistry
  name: nugetregistry-service
spec:
  type: ClusterIP
  selector:
    component: nugetregistry
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
