apiVersion: v1
kind: Service
metadata:
  name: nugetregistry-service
spec:
  type: ClusterIP
  selector:
    component: nugetregistry
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
