apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-api
  template:
    metadata:
      labels:
        app: questionnaire-api
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configmap":{"name":"questionnaire-bied-set","items":[{"key":"questionnaire.pb","path":"questionnaire.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
    spec:
      containers:
        - name: questionnaire-api
          image: "{{ .Values.global.services.questionnaire_api.name }}:{{ .Values.global.services.questionnaire_api.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "60m"
              memory: "512Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          ports:
            - containerPort: 5000
