apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-questionnaire
spec:
  databaseSecret:
    secretName: mongodb-questionnaire-secret
  version: "3.4-v3"
  storageType: Durable
  podTemplate:
    spec:
      readinessProbe:
        tcpSocket:
          port: 27017
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 27017
        initialDelaySeconds: 15
        periodSeconds: 30
    metadata:
      labels:
        app: mongodb
      annotations:
        sidecar.istio.io/inject: "false"
  storage:
    storageClassName: {{ .Values.global.storageClassName }}
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
        storage: 1Gi
      limits:
        cpu: "70m"
        memory: "512Mi"

  terminationPolicy: Delete
