apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-questionnaire
spec:
  databaseSecret:
    secretName: mongodb-questionnaire-secret
  version: "3.4-v3"
  storageType: Durable
  storage:
    # storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "512Mi"

  terminationPolicy: Resume
