apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec: 
      serviceAccountName: kafka
      containers:
        - name: kafka
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_LISTENERS
              value: INSIDE://9093,OUTSIDE://:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          
              
