apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    name: kafka  
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9092
  selector:
    name: kafka
