replicaCount: 1

image:
  repository: questionnaire-api:latest
  pullPolicy: IfNotPresent

containerPort: 3000
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "datasource-api"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  port: 80
  targetPort: 3000
