export const CREATE_QUESTIONNAIRE = '[QUESTIONNAIRE] Create'
export const ANSWER_QUESTION = '[QUESTIONNAIRE] Answer'
export const NEXT_SECTION = '[QUESTIONNAIRE] Next'
export const PREVIOUS_SECTION = '[QUESTIONNAIRE] Previous'