apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-api
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-api
  template:
    metadata:
      labels:
        io.kompose.service: user-api
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configmap":{"name":"user-bied-set","items":[{"key":"user.pb","path":"user.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
    spec:
      containers:
        - name: user-api
          image:  "{{ .Values.global.services.user_service.name }}:{{ .Values.global.services.user_service.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "60m"
              memory: "512Mi"
          ports:
            - containerPort: 5050
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5050
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
