apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  version: 8.0-v2
  databaseSecret:
    secretName: user-db-auth
  storageType: "Durable"
  storage:
    storageClassName: {{ .Values.global.storageClassName }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
      limits:
        cpu: "50m"
  podTemplate:
    metadata:
        annotations:
          sidecar.istio.io/inject: "false"
    spec:
      args:
        - --default-authentication-plugin=mysql_native_password
      env:
      - name: MYSQL_DATABASE
        value: user
  terminationPolicy: Delete
---
apiVersion: v1
kind: Secret
metadata:
  name:  user-db-auth
type: Opaque
data:
  user: cm9vdA==
  password: U3VwZXJsMzN0cGFzc3cwcmQh
