  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-api
spec:
  gateways:
    - bied-gateway
  hosts:
    - "{{ .Values.global.user.host }}" # What inbound Host should be routed. (eg. 'research.bied.nl')
  http:
    - match:
        - uri:
            prefix: "{{ .Values.global.user.route }}"
      rewrite:
        uri: /user
      route:
        # routes it toward this host. Usually a Kubernetes native 'Service', this should be a FQDN in production
        - destination:
            host: user-api
            port:
              number: 5050