apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: research-db
  name: research-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: research-db
  template:
    metadata:
      labels:
        io.kompose.service: research-db
    spec:
      containers:
        - name: research-db
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "50m"
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: SA_PASSWORD
              value: Superl33tpassw0rd!
       
