apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: research-api
spec:
  gateways:
    - bied-gateway
  hosts:
    - "{{ .Values.global.research.host }}" # What inbound Host should be routed. (eg. 'research.bied.nl')
  http:
    - match:
        - uri:
            prefix: {{ .Values.global.research.route }}
      rewrite:
        uri: "/research"
      route:
        # routes it toward this host. Usually a Kubernetes native 'Service', this should be a FQDN in production
        - destination:
            host: research-api
            port:
              number: 5050