apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datasource-api.fullname" . }}
  labels:
    {{- include "datasource-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "datasource-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "datasource-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: datasources-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.services.datasources_api.name }}:{{ .Values.global.services.datasources_api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "70m"
              memory: "512Mi"
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
              protocol: TCP
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-datasource-secret
                  key: password
