apiVersion: v1
kind: Service
metadata:
  namespace: email-service
  labels:
    app: email-service-service
  name: email-service-service
spec:
  ports:
    - name: grpc
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: email-service
