apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configmap":{"name":"email-bied-set","items":[{"key":"mail.pb","path":"mail.pb"}, {"key":"template.pb","path":"template.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: email-service
          image: "{{ .Values.global.services.email_service.name }}:{{ .Values.global.services.email_service.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          ports:
            - containerPort: 5000