apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ include "user.fullname" . }}
  name: {{ include "user.fullname" . }}
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    io.kompose.service: {{ include "user.fullname" . }}
