apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ include "user.fullname" . }}
  name: {{ include "user.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ include "user.fullname" . }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ include "user.fullname" . }}
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configmap":{"name":"user-bied-set","items":[{"key":"user.pb","path":"user.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
    spec:
      containers:
        - name: {{ include "user.fullname" . }}
          image: "{{ .Values.global.services.user.name }}:{{ .Values.global.services.user.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "50m"
          ports:
            - containerPort: 5050
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5050
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
